### ISSUE TITLE
More Documentation please...

### ISSUE THREAD

**Issue by Loki-Afro** [noroute/spring-boot-docker#1]
I am having trouble to run this project. And since this is the only complete example of springboot + docker I would like to contribute ;)

There are missing requirements, its not specified that we need gradle, even if its obviously, but which version? I am a maven user, I don't know that much about gradle yet :) But it seems like that nearly in all repositories there are only old versions available. So you have to install it by hand.

Your wrapper script does not work on my machine `Linux jessie 3.14-2-amd64 #1 SMP Debian 3.14.15-2 (2014-08-09) x86_64 GNU/Linux`

It simply fails with: `Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain`

The command that will be executed when calling `./gradlew build` is: `java -Dorg.gradle.appname=gradlew -classpath /root/spring-boot-docker/gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain build`

where  `/root/spring-boot-docker/gradle/wrapper/gradle-wrapper.jar` does not even exist.

What is the gradle wrapper supposed to do here?

My gradle version:

```
root@jessie:~/spring-boot-docker# gradle -version

------------------------------------------------------------
Gradle 1.12
------------------------------------------------------------

Build time:   2014-04-29 09:24:31 UTC
Build number: none
Revision:     a831fa866d46cbee94e61a09af15f9dd95987421

Groovy:       1.8.6
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
Ivy:          2.2.0
JVM:          1.8.0_20 (Oracle Corporation 25.20-b23)
OS:           Linux 3.14-2-amd64 amd64
```

However I can run `gradle build` and that works fine.

And this does only work with java 7, since you are installing java 7 in the container. Otherwise you would get an `java.lang.UnsupportedClassVersionError`.

**Comment by noroute** [comment]
Thanks @Loki-Afro for pointing this out. I actually forgot to also put the gradlew binaries into the repo which is required for gradlew to work correctly. This also takes care of downloading the correct version of Gradle (currently 1.11).

I also added a compatibility section to the docs that mentions the installation of Java7.

I hope this makes the dome easier to use.
